### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by Finnomator** [r-ex/rsx#10]
I was wondering if there are any plans to support Linux in the future?

**Comment by r-ex** [comment]
hi,
currently there are no plans to natively support linux, as RSX currently requires the use of some platform-specific dependencies such as Direct3D 11 for asset preview (and some others for texture processing/exporting).
it's not impossible that it will be considered in the future, however it is not a priority since the majority of players for reSource engine games (Titanfall, Titanfall 2, Apex Legends) are on some version of Windows.
